"""initialmigration

Revision ID: df59c71b87ad
Revises: 
Create Date: 2024-11-30 15:45:24.785652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'df59c71b87ad'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('modifiedAt', sa.DateTime(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('firstname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lastname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('category', sa.Column('createdAt', sa.DateTime(), nullable=False))
    op.add_column('category', sa.Column('modifiedAt', sa.DateTime(), nullable=False))
    op.add_column('item', sa.Column('createdAt', sa.DateTime(), nullable=False))
    op.add_column('item', sa.Column('modifiedAt', sa.DateTime(), nullable=False))
    op.add_column('item', sa.Column('user_id', sa.Integer(), nullable=False))
    op.alter_column('item', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'item', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'item', 'category', ['category_id'], ['id'])
    op.add_column('transaction', sa.Column('createdAt', sa.DateTime(), nullable=False))
    op.add_column('transaction', sa.Column('modifiedAt', sa.DateTime(), nullable=False))
    op.add_column('transaction', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'transaction', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'transaction', 'item', ['item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'user_id')
    op.drop_column('transaction', 'modifiedAt')
    op.drop_column('transaction', 'createdAt')
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.alter_column('item', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('item', 'user_id')
    op.drop_column('item', 'modifiedAt')
    op.drop_column('item', 'createdAt')
    op.drop_column('category', 'modifiedAt')
    op.drop_column('category', 'createdAt')
    op.drop_table('user')
    # ### end Alembic commands ###
